apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bot.fullname" . }}
  labels:
    {{- include "bot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bot.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: FAFBOT_PGSQL_CONNECTION
              value: "{{ .Values.telegram.PGSQL_STR }}"
            - name: TELEGRAM_APITOKEN
              value: "{{ .Values.telegram.TOKEN }}"
